spring.application.name=screener
server.port=8081

# ===============================
# DATABASE CONNECTION SETTINGS
# ===============================
# Connects to your Docker MySQL instance on localhost:3306
# 'createDatabaseIfNotExist=true' automatically creates the 'trading_db' database if it's missing
spring.datasource.url=jdbc:mysql://mysql-server:3306/trading_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata

# Username used in your Docker container (default is root)
spring.datasource.username=root

# Replace 'your_password' with the password you set in the MYSQL_ROOT_PASSWORD environment variable
spring.datasource.password=Pass@1234

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE SETTINGS
# ===============================
# 'update' automatically updates the database schema based on your Entity classes
spring.jpa.hibernate.ddl-auto=update

# Shows the SQL queries in the console for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Specifies the MySQL dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# FILE UPLOAD SETTINGS
# ===============================
# Set max file size for your Excel uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.kafka.bootstrap-servers=kafka-broker:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Custom property for your topic
kafka.topic.pdf-chunks=stock-pdf-chunks

spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.max.poll.interval.ms=900000
spring.kafka.consumer.max-poll-records=5

# ===============================
# OLLAMA CONFIGURATION
# ===============================
ollama.model=deepseek-coder-v2
ollama.temperature=0.7
ollama.top-k=40
ollama.top-p=0.95

# Comma-separated list of your active Ollama URLs
ollama.urls=https://parallactic-climatic-donte.ngrok-free.dev,https://nonadeptly-locustlike-zane.ngrok-free.dev/,https://worshiper-vehicular-neon.ngrok-free.dev
